### ISSUE TITLE
widukind-web an widukind-api failed to boot

### ISSUE THREAD

**Issue by lefakir** [Widukind/widukind-docker#13]
Hello, I tried to install widukind-docker and I encounter an error.
This is the same thing for Docker under MacOS and Linux.

Did you experience the same problem or have an idea ?

```
[2016-06-13 13:41:43 +0000] [1] [INFO] Starting gunicorn 19.6.0
[2016-06-13 13:41:43 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2016-06-13 13:41:43 +0000] [1] [INFO] Using worker: gevent_wsgi
[2016-06-13 13:41:43 +0000] [7] [INFO] Booting worker with pid: 7
[2016-06-13 13:41:44 +0000] [9] [INFO] Booting worker with pid: 9
[2016-06-13 13:41:44 +0000] [8] [INFO] Booting worker with pid: 8
[2016-06-13 13:41:44 +0000] [10] [INFO] Booting worker with pid: 10
[2016-06-13 13:41:44 +0000] [11] [INFO] Booting worker with pid: 11
[2016-06-13 13:41:44 +0000] [12] [INFO] Booting worker with pid: 12
[2016-06-13 13:41:44 +0000] [13] [INFO] Booting worker with pid: 13
[2016-06-13 13:41:44 +0000] [14] [INFO] Booting worker with pid: 14
[2016-06-13 13:41:44 +0000] [15] [INFO] Booting worker with pid: 15
[2016-06-13 13:41:49 +0000] [1] [INFO] Shutting down: Master
[2016-06-13 13:41:49 +0000] [1] [INFO] Reason: Worker failed to boot.
[2016-06-13 13:42:04 +0000] [1] [INFO] Starting gunicorn 19.6.0
[2016-06-13 13:42:04 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2016-06-13 13:42:04 +0000] [1] [INFO] Using worker: gevent_wsgi
[2016-06-13 13:42:04 +0000] [7] [INFO] Booting worker with pid: 7
[2016-06-13 13:42:04 +0000] [8] [INFO] Booting worker with pid: 8
[2016-06-13 13:42:04 +0000] [9] [INFO] Booting worker with pid: 9
[2016-06-13 13:42:04 +0000] [10] [INFO] Booting worker with pid: 10
[2016-06-13 13:42:04 +0000] [11] [INFO] Booting worker with pid: 11
[2016-06-13 13:42:04 +0000] [12] [INFO] Booting worker with pid: 12
[2016-06-13 13:42:04 +0000] [13] [INFO] Booting worker with pid: 13
[2016-06-13 13:42:04 +0000] [14] [INFO] Booting worker with pid: 14
[2016-06-13 13:42:04 +0000] [15] [INFO] Booting worker with pid: 15
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 196, in run
    self.sleep()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 346, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2016-06-13T13:42:08.489205211Z 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==19.6.0', 'console_scripts', 'gunicorn')()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 218, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 331, in halt
    self.stop()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 381, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2016-06-13 13:42:21 +0000] [1] [INFO] Starting gunicorn 19.6.0
[2016-06-13 13:42:21 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2016-06-13 13:42:21 +0000] [1] [INFO] Using worker: gevent_wsgi
[2016-06-13 13:42:21 +0000] [7] [INFO] Booting worker with pid: 7
[2016-06-13 13:42:21 +0000] [8] [INFO] Booting worker with pid: 8
[2016-06-13 13:42:21 +0000] [9] [INFO] Booting worker with pid: 9
[2016-06-13 13:42:21 +0000] [10] [INFO] Booting worker with pid: 10
[2016-06-13 13:42:21 +0000] [11] [INFO] Booting worker with pid: 11
[2016-06-13 13:42:21 +0000] [12] [INFO] Booting worker with pid: 12
[2016-06-13 13:42:21 +0000] [13] [INFO] Booting worker with pid: 13
[2016-06-13 13:42:21 +0000] [14] [INFO] Booting worker with pid: 14
[2016-06-13 13:42:21 +0000] [16] [INFO] Booting worker with pid: 16
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 196, in run
    self.sleep()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 346, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==19.6.0', 'console_scripts', 'gunicorn')()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 218, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 331, in halt
    self.stop()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 381, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2016-06-13 13:42:28 +0000] [1] [INFO] Starting gunicorn 19.6.0
[2016-06-13 13:42:28 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2016-06-13 13:42:28 +0000] [1] [INFO] Using worker: gevent_wsgi
[2016-06-13 13:42:28 +0000] [7] [INFO] Booting worker with pid: 7
[2016-06-13 13:42:28 +0000] [8] [INFO] Booting worker with pid: 8
[2016-06-13 13:42:28 +0000] [9] [INFO] Booting worker with pid: 9
[2016-06-13 13:42:29 +0000] [10] [INFO] Booting worker with pid: 10
[2016-06-13 13:42:29 +0000] [11] [INFO] Booting worker with pid: 11
[2016-06-13 13:42:29 +0000] [12] [INFO] Booting worker with pid: 12
[2016-06-13 13:42:29 +0000] [13] [INFO] Booting worker with pid: 13
[2016-06-13 13:42:29 +0000] [15] [INFO] Booting worker with pid: 15
[2016-06-13 13:42:29 +0000] [14] [INFO] Booting worker with pid: 14
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 196, in run
    self.sleep()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 346, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==19.6.0', 'console_scripts', 'gunicorn')()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 218, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 331, in halt
    self.stop()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 381, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2016-06-13 13:42:55 +0000] [1] [INFO] Starting gunicorn 19.6.0
[2016-06-13 13:42:55 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2016-06-13 13:42:55 +0000] [1] [INFO] Using worker: gevent_wsgi
[2016-06-13 13:42:55 +0000] [7] [INFO] Booting worker with pid: 7
[2016-06-13 13:42:55 +0000] [8] [INFO] Booting worker with pid: 8
[2016-06-13 13:42:55 +0000] [9] [INFO] Booting worker with pid: 9
[2016-06-13 13:42:55 +0000] [10] [INFO] Booting worker with pid: 10
[2016-06-13 13:42:55 +0000] [11] [INFO] Booting worker with pid: 11
[2016-06-13 13:42:55 +0000] [12] [INFO] Booting worker with pid: 12
[2016-06-13 13:42:55 +0000] [13] [INFO] Booting worker with pid: 13
[2016-06-13 13:42:55 +0000] [14] [INFO] Booting worker with pid: 14
[2016-06-13 13:42:55 +0000] [15] [INFO] Booting worker with pid: 15
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 196, in run
    self.sleep()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 346, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==19.6.0', 'console_scripts', 'gunicorn')()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 218, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 331, in halt
    self.stop()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 381, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.4/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by srault95** [comment]
helo, it's a bug from the last release of python Flask.

please wait a merge of pull request: https://github.com/Widukind/widukind-web/pull/25/commits/d268391152860ac5a0457e1888dadaf6bc2c110b

or apply this fixes:

```
$ vi widukind/web/requirements/default.txt
# add first line:  Flask==0.10.1

$ docker-compose up -d --force-recreate --no-deps --build web

Same bug for widukind-api.
```

**Comment by lefakir** [comment]
That's perfect, it works !
Nice project by the way, thank you very much.
